### ISSUE TITLE
Whatever you don't change to true will be locked even if you actually own the DLC

### ISSUE THREAD

**Issue by Roriketsu** [EastArctica/Payday-2-DLC-Unlocker#1]
I'm trying to enable only the Completely Overkill Pack because fuck paying $1800 for a legit copy when I only want 4 out of the 14 masks, but when I do every other DLC I own legit gets locked. I don't know and can't find the internal names of all the DLC, so I was hoping a solution could be brewed up or maybe a COP only DLC unlocker could be a thing.

**Comment by EastArctica** [comment]
Fixed in latest. Make a new issue if this persists.
